FROM node:erbium-alpine  as build-stage
WORKDIR /app
COPY package*.json ./

RUN npm install
COPY . .
COPY .env.production .env.production
RUN npm run build

# production stage
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/default.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]