version: '3.1'

services:
  ## uncomment in case need mongo docker

  # mongo:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - /Users/ravindrayadav/praticeMongodb:/data/db 
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: mongo
  #     MONGO_INITDB_ROOT_PASSWORD: mongo
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - mongo  
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: mongo

  reactjs-model:
    image: eeepoonam/incident_mgt_system:reactjs_frontend_1.0
    restart: always
    ports:
      - 80:80
    depends_on:
      - nodejs-model  

  nodejs-model:
    image: eeepoonam/incident_mgt_system:nodejs_backend_1.0
    restart: always
    ports:
      - 8082:8082
                
